DROP TABLE IF EXISTS VIDEO;
CREATE TABLE VIDEO (
                         ID VARCHAR2(50) PRIMARY KEY,
                         TITLE VARCHAR2(50) NOT NULL,
                         DESCRIPTION VARCHAR2(50),
                         UPLOAD_TIMESTAMP timestamp(6) NOT NULL,
                         UPDATED_TIMESTAMP timestamp(6) NOT NULL,
                         DURATION NUMBER NOT NULL,
                         LENGTH_PIXEL NUMBER NOT NULL,
                         WIDTH_PIXEL NUMBER NOT NULL,
                         FORMAT VARCHAR2(10) NOT NULL,
                         STATUS VARCHAR2(10)

);

CREATE INDEX ID on VIDEO(ID);

INSERT INTO VIDEO(ID, TITLE, DESCRIPTION, UPLOAD_TIMESTAMP, UPDATED_TIMESTAMP, DURATION, LENGTH_PIXEL, WIDTH_PIXEL, FORMAT, STATUS) VALUES ('TEST001','TESTVIDEO','TEST VIDEO METADATA', '2024-04-15 05:21:18.219169', '2024-04-15 05:21:18.219169', '1', '1920','1080', 'MP4','');